FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY **/*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Poc.TestesIntegradosJep.dll"]


COMANDOS LINUX
#RUN find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
#RUN ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
chown -R ubuntu:www-data sostenes/

REMOVER Imagens None
docker image rm $(docker image ls -f 'dangling=true' -q)

COMANDO DOCKER
docker build -t aspnetapp .
docker run -d -p 8080:80 --name myapp aspnetapp
docker rmi $id_imagem 
docker rm $id_container
docker save -o <path for generated tar file> <image name>
docker load -i <path to image tar file>