{
 "title": "Shoe Hub",
 "description": "All the graphs of Shoe Hub Company",
 "tags": [
  "business",
  "tech"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "countryCode", "label": "Country", "query": "stats.gauges.shoehub.*" }
  ]
 },
 "panels": [
  {
   "title": "Panel Alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Refound $countryCode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "countryCode",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 2,
     "target": "aliasByNode(stats.gauges.shoehub.$countryCode.refunds, 3, 4)"
    }
   ]
  },
  {
   "title": "Stat Refound Australia",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "stats.gauges.shoehub.AU.refunds"
    }
   ]
  },
  {
   "title": "Shoe Hub Total Sales",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats_counts.shoehub.sales.*" }
   ]
  },
  {
   "title": "Compara data series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats_counts.shoehub.sales.Boots"
    },
    {
     "target": "timeShift(stats_counts.shoehub.sales.Boots, '10s')"
    }
   ]
  },
  {
   "title": "Gauge Refouns",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.shoehub.*.refunds, 3, 4)"
    }
   ]
  },
  {
   "title": "Bar Gage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.shoehub.*.payments.Cash, 3, 5)"
    }
   ]
  },
  {
   "title": "Pie Chart Refunds",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.shoehub.*.refunds, 3, 4)"
    }
   ]
  }
 ]
}