// <auto-generated />
using System;
using Estudos.Repositorio.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Estudos.Repositorio.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20190201010055_Versao 1.00")]
    partial class Versao100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Estudos.Dominio.Entidades.Entidades_Cardapio.Cardapio", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Card_Codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCardapioCategoria")
                        .HasColumnName("CardCat_Codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("Card_Descricao")
                        .HasMaxLength(100);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("Card_Titulo")
                        .HasMaxLength(100);

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCardapioCategoria");

                    b.ToTable("Cardapio");
                });

            modelBuilder.Entity("Estudos.Dominio.Entidades.Entidades_Cardapio.CardapioCategoria", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CardCat_Codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("CardCat_Descricao")
                        .HasMaxLength(100);

                    b.HasKey("Codigo");

                    b.ToTable("Cardapio_Categoria");
                });

            modelBuilder.Entity("Estudos.Dominio.Entidades.Entidades_Pedido.Pedido", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Ped_Codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCardapio")
                        .HasColumnName("Card_Codigo");

                    b.Property<int>("CodigoPedidoCompleto")
                        .HasColumnName("PedComp_Codigo");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnName("Ped_Observacao")
                        .HasMaxLength(100);

                    b.Property<int>("Quantidade");

                    b.Property<decimal>("ValorTotalPedido")
                        .HasColumnName("Ped_ValorTotalPedido")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCardapio");

                    b.HasIndex("CodigoPedidoCompleto");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Estudos.Dominio.Entidades.Entidades_Pedido.PedidoCompleto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PedComp_Codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoMesa")
                        .HasColumnName("PedComp_CodigoMesa");

                    b.Property<DateTime>("Data")
                        .HasColumnName("PedComp_Data");

                    b.Property<string>("NomeMesa")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("TipoPagamento")
                        .HasColumnName("PedComp_TipoPagamento");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnName("PedComp_ValorTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValorTroco")
                        .HasColumnName("PedComp_ValorTroco");

                    b.HasKey("Codigo");

                    b.ToTable("Pedido_Completo");
                });

            modelBuilder.Entity("Estudos.Dominio.Entidades.Entidades_Cardapio.Cardapio", b =>
                {
                    b.HasOne("Estudos.Dominio.Entidades.Entidades_Cardapio.CardapioCategoria", "CardapioCategoria")
                        .WithMany("Cardapios")
                        .HasForeignKey("CodigoCardapioCategoria")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Estudos.Dominio.Entidades.Entidades_Pedido.Pedido", b =>
                {
                    b.HasOne("Estudos.Dominio.Entidades.Entidades_Cardapio.Cardapio", "Cardapio")
                        .WithMany("Pedidos")
                        .HasForeignKey("CodigoCardapio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Estudos.Dominio.Entidades.Entidades_Pedido.PedidoCompleto", "PedidoCompleto")
                        .WithMany("Pedidos")
                        .HasForeignKey("CodigoPedidoCompleto")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
