version: "3.4"

services:
  
  zookeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeper
    networks:
      - network-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    networks:
      - network-kafka
    depends_on:
      - zookeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafkadrop:
    image: obsidiandynamics/kafdrop:3.30.0
    container_name: kafkadrop
    networks:
      - network-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  FacialBiometricsStatusInitKafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: FacialBiometricsStatusInitKafka
    networks:
      - network-kafka
    depends_on:
      - kafka
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
         # blocks until kafka is reachable
         kafka-topics --bootstrap-server kafka:29092 --list

         echo -e 'Creating kafka topics'
         kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-in --replication-factor 1 --partitions 1               

        echo -e 'Creating consumer groups to topic'
        kafka-console-consumer --bootstrap-server kafka:29092 --topic topic-in --group test-in        
        echo -e 'Successfully created consumer groups'

        echo -e 'Successfully created the following topics and consumer groups:'
        kafka-topics --bootstrap-server kafka:29092 --list
      "

networks:
  network-kafka:
    driver: bridge       